#pragma kernel CSMain

int Width;
int Height;

struct uvItem {
	float2 uv;
	int index;
};

StructuredBuffer<int> isDelete;
StructuredBuffer<uvItem> UV;
AppendStructuredBuffer<int> DeleteVertexIndex;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    int x = int(abs(frac(UV[id.x].uv.x)) * Width);
    int y = int(abs(frac(UV[id.x].uv.y)) * Height);

	if (isDelete[y * Width + x] == 1) 
	{
		DeleteVertexIndex.Append(UV[id.x].index);
	}
}
